### ISSUE TITLE
update site

### ISSUE THREAD

**Issue by ghost** [philglover/pitclipse#59]
It seems the update site is down (I get a 404 error). Can you please investigate?

**Comment by taichi** [comment]
:+1:

**Comment by hcoles** [comment]
I don't think the site is down. If you hit the URL with a browser you'll get a 404, but it appears to work fine from the eclipse update manager.

Think it might need an index.html page adding to avoid the confusion.

**Comment by philglover** [comment]
I've updated the readme.  The preferred way to install is via Eclipse marketplace.  The update site is not viewable from a browser.

I have just tried the update site from an eclipse install locally and it seemed to work.   Can you confirm and close the issue?

Thanks

**Comment by taichi** [comment]
i already solve the problem.
