### ISSUE TITLE
Problem installing it into STS

### ISSUE THREAD

**Issue by jfcorugedo** [philglover/pitclipse#60]
Whenever I try to install it into an STS 3.7.1 I alway get the following error:

No repository found containing: osgi.bundle,org.springframework.roo.wrapping.protobuf-java-lite,2.3.0.0001

**Comment by philglover** [comment]
I use an older version of STS on debian with no issues.  Pitclipse doesn't have any dependencies on those packages so I can only assume this error is coming from the STS update site itself.  Have you been able to install any other plugins?

I will try to install 3.7.1 locally but won't have a chance to do this until next week.

**Comment by philglover** [comment]
I have installed STS 3.7.1 on debian, installed the plugin from market place and can run PIT with no issues.  Can you confirm if you are still having issues?

**Comment by jfcorugedo** [comment]
Yes, from marketplace I didn't have any problem.

Thanks!
