### ISSUE TITLE
Directory does not exist

### ISSUE THREAD

**Issue by marcelsinniger** [philglover/pitclipse#65]
Hi,

I get an error message about an incorrect path when I run a JUnit test with PITclipse (Run As -> PIT mutation test):
![image](https://cloud.githubusercontent.com/assets/4046828/15704119/67c6c4f0-27e9-11e6-8e7f-8617fa24621c.png)

I have two projects:
- One project with the code to mutate (source folder => C:\Users\msi\workspace\PITest Code to mutate\src)
- A Second project with the JUnit tests (source folder => C:\Users\msi\workspace\PITest Test Projects\src). The second project includes the source folder from the first project so that it knows the classes to test.

With that configuration, I get the error message mentioned above.

Regards Marcel

**Comment by philglover** [comment]
Revisiting the code that checks the classpath.  will let you know what I find.

**Comment by philglover** [comment]
I have been able to recreate this manually by creating a source dir and then deleting it from the file system directly (while it still shows in eclipse).

A fix should be released shortly, in the meantime you can resolve this yourself by refreshing your project or deleting the unused source directory.
